version: "2"
services:
  kvserver1:
    image: kvserver:latest
    container_name: kvserver-8081
    ports:
      - 8081:8081
    environment:
      - "serverPort=8081"
      - "serverPeers=kvserver-8081:8081:1,kvserver-8082:8082:2,kvserver-8083:8083:3"
      - "logging.file.name=kvserver-8081.log"
  kvserver2:
    image: kvserver:latest
    container_name: kvserver-8082
    ports:
      - 8082:8082
    environment:
      - "serverPort=8082"
      - "serverPeers=kvserver-8081:8081:1,kvserver-8082:8082:2,kvserver-8083:8083:3"
      - "logging.file.name=kvserver-8082.log"
  kvserver3:
    image: kvserver:latest
    container_name: kvserver-8083
    ports:
      - 8083:8083
    environment:
      - "serverPort=8083"
      - "serverPeers=kvserver-8081:8081:1,kvserver-8082:8082:2,kvserver-8083:8083:3"
      - "logging.file.name=kvserver-8083.log"
